# ruff does not have Python 3.6, Python 3.7 should make the job
target-version = "py37"

[lint]
extend-select = [
    "I",  # Sort imports
]
ignore = [
    "E721",  # Do not compare types, use `isinstance()`
]

[lint.isort]
split-on-trailing-comma = false

[format]
skip-magic-trailing-comma = true
line-ending = "lf"
docstring-code-format = true
