version: '3'

volumes:
  data15:
  run15:

  data13:
  run13:

  data11:
  run11:

  data96:
  run96:


services:
  ui:
    image: dalibo/temboard:8
    environment:
      # These PG* vars are for auto_configure.sh
      PGHOST: repository
      PGUSER: postgres
      PGPASSWORD: postgres
      TEMBOARD_LOGGING_LEVEL: DEBUG
    links:
      - repository
    ports:
      - "8888:8888"

  repository:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: [
      postgres,
      -c, log_connections=on,
      -c, log_statement=all,
      -c, "log_line_prefix=%m [%p]: [%l-1] app=%a,db=%d,client=%h,user=%u ",
      -c, cluster_name=repository,
    ]

  instance15:
    image: postgres:15-alpine
    command: [
      postgres,
      -c, shared_preload_libraries=pg_stat_statements,
      -c, log_connections=on,
      -c, log_statement=all,
      -c, "log_line_prefix=%m [%p]: [%l-1] app=%a,db=%d,client=%h,user=%u ",
      -c, cluster_name=instance15,
    ]
    ports:
      - 5432:5432
    volumes:
    - data15:/var/lib/postgresql/data
    - run15:/var/run/postgresql
    environment:
      POSTGRES_PASSWORD: postgres

  agent15:
    image: dalibo/temboard-agent:8
    volumes:
    - data15:/var/lib/postgresql/data
    - run15:/var/run/postgresql/
    - /var/run/docker.sock:/var/run/docker.sock
    links:
    - instance15:instance15.acme.tld
    - ui
    environment: &agent-env
      TEMBOARD_HOSTNAME: instance15.acme.tld
      TEMBOARD_UI_URL: https://ui:8888/
      TEMBOARD_UI_USER: admin
      TEMBOARD_UI_PASSWORD: admin
      TEMBOARD_LOGGING_LEVEL: DEBUG
      PGPASSWORD: postgres

  instance13:
    image: postgres:13-alpine
    ports:
      - 5433:5432
    volumes:
      - data13:/var/lib/postgresql/data
      - run13:/var/run/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
    command: [
      postgres,
      -c, shared_preload_libraries=pg_stat_statements,
      -c, log_connections=on,
      -c, log_statement=all,
      -c, "log_line_prefix=%m [%p]: [%l-1] app=%a,db=%d,client=%h,user=%u ",
      -c, cluster_name=instance13,
    ]

  agent13:
    image: dalibo/temboard-agent:8
    volumes:
      - data13:/var/lib/postgresql/data
      - run13:/var/run/postgresql/
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - instance13:instance13.acme.tld
      - ui
    environment:
      <<: *agent-env
      TEMBOARD_HOSTNAME: instance13.acme.tld

  instance11:
    image: postgres:11-alpine
    ports:
      - 5434:5432
    volumes:
      - data11:/var/lib/postgresql/data
      - run11:/var/run/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
    command: [
      postgres,
      -c, shared_preload_libraries=pg_stat_statements,
      -c, log_connections=on,
      -c, log_statement=all,
      -c, "log_line_prefix=%m [%p]: [%l-1] app=%a,db=%d,client=%h,user=%u ",
      -c, cluster_name=instance11,
    ]

  agent11:
    image: dalibo/temboard-agent:8
    volumes:
      - data11:/var/lib/postgresql/data
      - run11:/var/run/postgresql/
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - instance11:instance11.acme.tld
      - ui
    environment:
      <<: *agent-env
      TEMBOARD_HOSTNAME: instance11.acme.tld

  instance96:
    image: postgres:9.6-alpine
    ports:
      - 5435:5432
    volumes:
      - data96:/var/lib/postgresql/data
      - run96:/var/run/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
    command: [
      postgres,
      -c, shared_preload_libraries=pg_stat_statements,
      -c, log_connections=on,
      -c, log_statement=all,
      -c, "log_line_prefix=%m [%p]: [%l-1] app=%a,db=%d,client=%h,user=%u ",
      -c, cluster_name=instance96,
    ]

  agent96:
    image: dalibo/temboard-agent:8
    volumes:
      - data96:/var/lib/postgresql/data
      - run96:/var/run/postgresql/
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - instance96:instance96.acme.tld
      - ui
    environment:
      <<: *agent-env
      TEMBOARD_HOSTNAME: instance96.acme.tld
